import { ChannelItem, MovieItem, Playlist } from '../types';

export const STARTER_PLAYLIST_ID = 'playlist-starter-curated';

export const STARTER_PLAYLIST: Playlist = {
  id: STARTER_PLAYLIST_ID,
  name: 'StreamGlass Curated Stream Collection',
  sourceType: 'curated',
  channelCount: 10,
  movieCount: 6,
  groups: ['News & Current Affairs', 'Science & Tech', 'Movies & Cinema', 'Sports & Action', 'Culture & World'],
  createdAt: Date.now() - 86400000 * 2,
  updatedAt: Date.now(),
  enabled: true,
};

export const SAMPLE_CHANNELS: ChannelItem[] = [
  {
    id: 'ch-trt',
    name: 'TRT World HD Live',
    url: 'https://tv-trtworld.medya.trt.com.tr/master.m3u8',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=150&auto=format&fit=crop&q=80',
    group: 'News & Current Affairs',
    tvgId: 'TRTWorld.tr',
    tvgName: 'TRT World',
    country: 'TR',
    language: 'English',
    playlistId: STARTER_PLAYLIST_ID,
    isLive: true,
    resolution: 'FHD',
    currentProgram: {
      title: 'World News Dispatch & Live Correspondents',
      description: 'Global geopolitical analysis, human stories, and live breaking coverage from international bureaus.',
      startTime: Date.now() - 15 * 60 * 1000,
      endTime: Date.now() + 45 * 60 * 1000,
    },
  },
  {
    id: 'ch-dw',
    name: 'Deutsche Welle (DW English)',
    url: 'https://dwamdstream102.akamaized.net/hls/live/2015525/dwstream102/index.m3u8',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=150&auto=format&fit=crop&q=80',
    group: 'News & Current Affairs',
    tvgId: 'DW.en',
    tvgName: 'DW English',
    country: 'DE',
    language: 'English',
    playlistId: STARTER_PLAYLIST_ID,
    isLive: true,
    resolution: 'FHD',
    currentProgram: {
      title: 'DW News & Global Insights',
      description: 'European perspectives, investigative journalism, culture, and science features from around the globe.',
      startTime: Date.now() - 25 * 60 * 1000,
      endTime: Date.now() + 35 * 60 * 1000,
    },
  },
  {
    id: 'ch-cgtn',
    name: 'CGTN Global News',
    url: 'https://news.cgtn.com/resource/live/english/cgtn-news.m3u8',
    logo: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=150&auto=format&fit=crop&q=80',
    group: 'News & Current Affairs',
    tvgId: 'CGTN.en',
    tvgName: 'CGTN News',
    country: 'CN',
    language: 'English',
    playlistId: STARTER_PLAYLIST_ID,
    isLive: true,
    resolution: 'FHD',
    currentProgram: {
      title: 'Global Watch & Economic Pulse',
      description: 'Worldwide markets, technology summits, developing nation perspectives, and trade development.',
      startTime: Date.now() - 10 * 60 * 1000,
      endTime: Date.now() + 50 * 60 * 1000,
    },
  },
  {
    id: 'ch-redbull',
    name: 'Red Bull TV Action Stream',
    url: 'https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8',
    logo: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?w=150&auto=format&fit=crop&q=80',
    group: 'Sports & Action',
    tvgId: 'RedBull.tv',
    tvgName: 'Red Bull TV',
    country: 'AT',
    language: 'English',
    playlistId: STARTER_PLAYLIST_ID,
    isLive: true,
    resolution: '1080p' as any,
    currentProgram: {
      title: 'Cliff Diving & Extreme Sports Tour',
      description: 'High-adrenaline action sports, athletic feats, surf expeditions, and behind-the-scenes athlete documentaries.',
      startTime: Date.now() - 30 * 60 * 1000,
      endTime: Date.now() + 30 * 60 * 1000,
    },
  },
  {
    id: 'ch-golf',
    name: '30A Pro Golf Network',
    url: 'https://30a-tv.com/feeds/vidaa/golf.m3u8',
    logo: 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=150&auto=format&fit=crop&q=80',
    group: 'Sports & Action',
    tvgId: 'Golf.us',
    tvgName: 'Pro Golf TV',
    country: 'US',
    language: 'English',
    playlistId: STARTER_PLAYLIST_ID,
    isLive: true,
    resolution: 'HD',
    currentProgram: {
      title: 'Championship Course Previews & Swing Mechanics',
      description: 'Pro tour coverage, masterclass swing breakdowns, coastal fairway showcases, and tournament highlights.',
      startTime: Date.now() - 5 * 60 * 1000,
      endTime: Date.now() + 55 * 60 * 1000,
    },
  },
  {
    id: 'ch-arirang',
    name: 'Arirang World Culture TV',
    url: 'https://amdlive-ch01-ctnd-com.akamaized.net/arirang_1ch/smil:arirang_1ch.smil/playlist.m3u8',
    logo: 'https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=150&auto=format&fit=crop&q=80',
    group: 'Culture & World',
    tvgId: 'Arirang.tv',
    tvgName: 'Arirang World',
    country: 'KR',
    language: 'English',
    playlistId: STARTER_PLAYLIST_ID,
    isLive: true,
    resolution: 'HD',
    currentProgram: {
      title: 'Seoul Culture Beat & Art Studio',
      description: 'Arts, design, culinary expeditions, pop culture phenomenon, and international cultural exchanges.',
      startTime: Date.now() - 12 * 60 * 1000,
      endTime: Date.now() + 48 * 60 * 1000,
    },
  },
  {
    id: 'ch-luxelife',
    name: 'LuxeLife Travel & Culture',
    url: 'https://30a-tv.com/feeds/vidaa/luxelife.m3u8',
    logo: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=150&auto=format&fit=crop&q=80',
    group: 'Culture & World',
    tvgId: 'LuxeLife.tv',
    tvgName: 'LuxeLife TV',
    country: 'US',
    language: 'English',
    playlistId: STARTER_PLAYLIST_ID,
    isLive: true,
    resolution: 'HD',
    currentProgram: {
      title: 'Mediterranean Coastal Retreats & Gastronomy',
      description: 'Exclusive resort destinations, Michelin culinary journeys, yacht expeditions, and design architecture.',
      startTime: Date.now() - 20 * 60 * 1000,
      endTime: Date.now() + 40 * 60 * 1000,
    },
  },
  {
    id: 'ch-30atv',
    name: '30A Prime Entertainment',
    url: 'https://30a-tv.com/feeds/xodglobal/30atv.m3u8',
    logo: 'https://images.unsplash.com/photo-1495020689067-958852a7765e?w=150&auto=format&fit=crop&q=80',
    group: 'Entertainment & Lifestyle',
    tvgId: '30APrime.tv',
    tvgName: '30A Prime',
    country: 'US',
    language: 'English',
    playlistId: STARTER_PLAYLIST_ID,
    isLive: true,
    resolution: 'HD',
    currentProgram: {
      title: 'Coastal Summer Festival & Live Acoustic Sessions',
      description: 'Beachside music, artist interviews, coastal living, community spotlights, and independent films.',
      startTime: Date.now() - 8 * 60 * 1000,
      endTime: Date.now() + 52 * 60 * 1000,
    },
  },
  {
    id: 'ch-bunny-stream',
    name: 'CineLoop 24/7 Cinema HD',
    url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    logo: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=150&auto=format&fit=crop&q=80',
    group: 'Movies & Cinema',
    tvgId: 'CineLoop.tv',
    tvgName: 'CineLoop HD',
    country: 'NL',
    language: 'English',
    playlistId: STARTER_PLAYLIST_ID,
    isLive: true,
    resolution: 'FHD',
    currentProgram: {
      title: 'Open Source Animation Retrospective',
      description: 'Showcasing world-class open render animations, character rigging, and surround audio testing.',
      startTime: Date.now() - 18 * 60 * 1000,
      endTime: Date.now() + 42 * 60 * 1000,
    },
  },
  {
    id: 'ch-scitech',
    name: 'Sci-Tech Quantum World',
    url: 'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8',
    logo: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=150&auto=format&fit=crop&q=80',
    group: 'Science & Tech',
    tvgId: 'SciTech.tv',
    tvgName: 'Sci-Tech Live',
    country: 'NL',
    language: 'English',
    playlistId: STARTER_PLAYLIST_ID,
    isLive: true,
    resolution: '4K',
    currentProgram: {
      title: 'Autonomous Robotics & Holographic Neural Networks',
      description: 'Applied robotics experiments, neural network visualizers, spatial computing, and cybernetic science.',
      startTime: Date.now() - 50 * 60 * 1000,
      endTime: Date.now() + 10 * 60 * 1000,
    },
  },
];

export const SAMPLE_MOVIES: MovieItem[] = [
  {
    id: 'mov-tears-of-steel',
    title: 'Tears of Steel',
    url: 'https://demo.unified-streaming.com/k8s/features/stable/video/tears-of-steel/tears-of-steel.ism/.m3u8',
    poster: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80',
    genre: ['Sci-Fi', 'Action', 'Cyberpunk'],
    year: 2012,
    duration: 734, // 12 mins
    description: 'In a dystopian future, a group of rebel warriors and eccentric scientists gather at the Oude Kerk in Amsterdam to stage a desperate holographic intervention and prevent an impending robot apocalypse.',
    rating: 4.8,
    playlistId: STARTER_PLAYLIST_ID,
    source: 'curated',
    resolution: '4K',
  },
  {
    id: 'mov-oceans',
    title: 'Oceans: The Living Deep',
    url: 'https://vjs.zencdn.net/v/oceans.mp4',
    poster: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=600&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=1600&auto=format&fit=crop&q=80',
    genre: ['Documentary', 'Nature', 'Cinema'],
    year: 2018,
    duration: 864, // 14 mins
    description: 'A breathtaking cinematic dive into the world’s most remote marine trenches, bioluminescent coral reefs, and apex ocean predators captured in high-definition panoramic cinematography.',
    rating: 4.9,
    playlistId: STARTER_PLAYLIST_ID,
    source: 'curated',
    resolution: 'FHD',
  },
  {
    id: 'mov-big-buck-bunny',
    title: 'Big Buck Bunny',
    url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    poster: 'https://images.unsplash.com/photo-1589656966895-2f33e7653819?w=600&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1600&auto=format&fit=crop&q=80',
    genre: ['Animation', 'Comedy', 'Family'],
    year: 2008,
    duration: 596, // 10 mins
    description: 'A large, gentle rabbit wakes up to enjoy the spring morning and beautiful forest butterflies, only to find peace disrupted by three bullying forest critters. He sets up an ingenious vengeance contraption.',
    rating: 4.7,
    playlistId: STARTER_PLAYLIST_ID,
    source: 'curated',
    resolution: 'FHD',
  },
  {
    id: 'mov-blue-moon',
    title: 'View From A Blue Moon',
    url: 'https://cdn.plyr.io/static/demo/View_From_A_Blue_Moon_Trailer-1080p.mp4',
    poster: 'https://images.unsplash.com/photo-1502680390469-be75c86b636f?w=600&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1470240731273-7821a6eeb6bd?w=1600&auto=format&fit=crop&q=80',
    genre: ['Action', 'Sports', 'Adventure'],
    year: 2015,
    duration: 720,
    description: 'Follow world-renowned surfer John Florence across the globe from South Pacific breaks to remote Alaskan coastlines in groundbreaking 4K sports cinematography.',
    rating: 4.9,
    playlistId: STARTER_PLAYLIST_ID,
    source: 'curated',
    resolution: 'FHD',
  },
  {
    id: 'mov-cosmic-drift',
    title: 'Cosmic Drift: BipBop Cinema',
    url: 'https://devstreaming-cdn.apple.com/videos/streaming/examples/bipbop_16x9/bipbop_16x9_variant.m3u8',
    poster: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80',
    genre: ['Sci-Fi', 'Audio Visual', 'Technology'],
    year: 2022,
    duration: 600,
    description: 'An audiovisual engineering master test featuring 16:9 adaptive multi-bitrate streams, calibrated color sweeps, and surround audio verification.',
    rating: 4.6,
    playlistId: STARTER_PLAYLIST_ID,
    source: 'curated',
    resolution: 'HD',
  },
  {
    id: 'mov-forest-odyssey',
    title: 'Forest Odyssey (Spring)',
    url: 'https://raw.githubusercontent.com/bower-media-samples/big-buck-bunny-1080p-30s/master/video.mp4',
    poster: 'https://images.unsplash.com/photo-1448375240586-882707db888b?w=600&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1511497584788-87676104235f?w=1600&auto=format&fit=crop&q=80',
    genre: ['Nature', 'Animation', 'Short'],
    year: 2019,
    duration: 300,
    description: 'A poetic celebration of waking flora and fauna in high-density European woodlands rendered with intricate particle physics.',
    rating: 4.8,
    playlistId: STARTER_PLAYLIST_ID,
    source: 'curated',
    resolution: 'FHD',
  },
];

export const SAMPLE_M3U_TEMPLATE = `#EXTM3U x-tvg-url="https://iptv-org.github.io/epg/guides/us.guide.xml"
#EXTINF:-1 tvg-id="TRTWorld.tr" tvg-name="TRT World" tvg-logo="https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=150" group-title="News & Current Affairs" tvg-country="TR",TRT World HD Live
https://tv-trtworld.medya.trt.com.tr/master.m3u8

#EXTINF:-1 tvg-id="DW.en" tvg-name="DW English" tvg-logo="https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=150" group-title="News & Current Affairs" tvg-country="DE",Deutsche Welle HD Broadcast
https://dwamdstream102.akamaized.net/hls/live/2015525/dwstream102/index.m3u8

#EXTINF:-1 tvg-id="CGTN.en" tvg-name="CGTN News" tvg-logo="https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=150" group-title="News & Current Affairs" tvg-country="CN",CGTN Global News
https://news.cgtn.com/resource/live/english/cgtn-news.m3u8

#EXTINF:-1 tvg-id="RedBull.tv" tvg-name="Red Bull TV" tvg-logo="https://images.unsplash.com/photo-1517649763962-0c623266ddc0?w=150" group-title="Action & Sports" tvg-country="AT",Red Bull TV Action Stream
https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8

#EXTINF:-1 tvg-id="Golf.us" tvg-name="Pro Golf TV" tvg-logo="https://images.unsplash.com/photo-1535131749006-b7f58c99034b?w=150" group-title="Action & Sports" tvg-country="US",30A Pro Golf Network
https://30a-tv.com/feeds/vidaa/golf.m3u8

#EXTINF:-1 tvg-id="Arirang.tv" tvg-name="Arirang World" tvg-logo="https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=150" group-title="Culture & World" tvg-country="KR",Arirang World Culture TV
https://amdlive-ch01-ctnd-com.akamaized.net/arirang_1ch/smil:arirang_1ch.smil/playlist.m3u8

#EXTINF:-1 tvg-id="CineLoop.tv" tvg-name="CineLoop HD" tvg-logo="https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=150" group-title="Movies & Cinema" tvg-country="NL",CineLoop 24/7 Cinema HD
https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8
`;
