import { ChannelItem, MovieItem, Playlist } from '../types';

export const STARTER_PLAYLIST_ID = 'playlist-starter-curated';

export const STARTER_PLAYLIST: Playlist = {
  id: STARTER_PLAYLIST_ID,
  name: 'StreamGlass Curated Stream Collection',
  sourceType: 'curated',
  channelCount: 10,
  movieCount: 6,
  groups: ['News & Current Affairs', 'Science & Tech', 'Movies & Cinema', 'Sports & Action', 'Culture & World'],
  createdAt: Date.now() - 86400000 * 2,
  updatedAt: Date.now(),
  enabled: true,
};

export const SAMPLE_CHANNELS: ChannelItem[] = [
  {
    id: 'ch-nasa',
    name: 'NASA TV Live',
    url: 'https://ntv1.akamaized.net/hls/live/2014075/NASA-NTV1-HLS/master.m3u8',
    logo: 'https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?w=150&auto=format&fit=crop&q=80',
    group: 'Science & Tech',
    tvgId: 'NASA.tv',
    tvgName: 'NASA TV',
    country: 'US',
    language: 'English',
    playlistId: STARTER_PLAYLIST_ID,
    isLive: true,
    resolution: 'FHD',
    currentProgram: {
      title: 'International Space Station Expedition Live',
      description: 'Live views of Earth from the ISS, astronaut activities, spacewalk operations and mission control audio.',
      startTime: Date.now() - 15 * 60 * 1000,
      endTime: Date.now() + 45 * 60 * 1000,
    },
  },
  {
    id: 'ch-bloomberg',
    name: 'Bloomberg Quicktake Live',
    url: 'https://bblive-lh.akamaihd.net/i/bloomberg_live1@106822/master.m3u8',
    logo: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=150&auto=format&fit=crop&q=80',
    group: 'News & Current Affairs',
    tvgId: 'Bloomberg.us',
    tvgName: 'Bloomberg News',
    country: 'US',
    language: 'English',
    playlistId: STARTER_PLAYLIST_ID,
    isLive: true,
    resolution: 'HD',
    currentProgram: {
      title: 'Global Financial Markets & Technology Bell',
      description: 'In-depth analysis of worldwide equities, currencies, commodities, and modern tech innovation.',
      startTime: Date.now() - 25 * 60 * 1000,
      endTime: Date.now() + 35 * 60 * 1000,
    },
  },
  {
    id: 'ch-france24',
    name: 'France 24 International',
    url: 'https://static.france24.com/live/F24_EN_LO_HLS/live_tv.m3u8',
    logo: 'https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=150&auto=format&fit=crop&q=80',
    group: 'News & Current Affairs',
    tvgId: 'France24.en',
    tvgName: 'France 24',
    country: 'FR',
    language: 'English',
    playlistId: STARTER_PLAYLIST_ID,
    isLive: true,
    resolution: 'FHD',
    currentProgram: {
      title: 'The World This Hour & In-Depth Report',
      description: 'Comprehensive international news coverage with European perspective and live field reporters.',
      startTime: Date.now() - 10 * 60 * 1000,
      endTime: Date.now() + 20 * 60 * 1000,
    },
  },
  {
    id: 'ch-dw',
    name: 'Deutsche Welle (DW English)',
    url: 'https://dwamdstream102.akamaized.net/hls/live/2015525/dwstream102/index.m3u8',
    logo: 'https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=150&auto=format&fit=crop&q=80',
    group: 'News & Current Affairs',
    tvgId: 'DW.en',
    tvgName: 'DW English',
    country: 'DE',
    language: 'English',
    playlistId: STARTER_PLAYLIST_ID,
    isLive: true,
    resolution: 'FHD',
    currentProgram: {
      title: 'DW News & Global Insights',
      description: 'World stories, investigative journalism, culture, and environmental features from around the globe.',
      startTime: Date.now() - 40 * 60 * 1000,
      endTime: Date.now() + 20 * 60 * 1000,
    },
  },
  {
    id: 'ch-aljazeera',
    name: 'Al Jazeera English Live',
    url: 'https://live-hls-web-aje.getaj.net/AJE/03.m3u8',
    logo: 'https://images.unsplash.com/photo-1526470608268-f674ce90ebd4?w=150&auto=format&fit=crop&q=80',
    group: 'News & Current Affairs',
    tvgId: 'AlJazeera.en',
    tvgName: 'Al Jazeera English',
    country: 'QA',
    language: 'English',
    playlistId: STARTER_PLAYLIST_ID,
    isLive: true,
    resolution: 'HD',
    currentProgram: {
      title: 'Live Global News Hour',
      description: 'Spotlighting under-reported regions, geopolitical developments, and live breaking alerts.',
      startTime: Date.now() - 5 * 60 * 1000,
      endTime: Date.now() + 55 * 60 * 1000,
    },
  },
  {
    id: 'ch-redbull',
    name: 'Red Bull TV Action Stream',
    url: 'https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8',
    logo: 'https://images.unsplash.com/photo-1517649763962-0c623266ddc0?w=150&auto=format&fit=crop&q=80',
    group: 'Sports & Action',
    tvgId: 'RedBull.tv',
    tvgName: 'Red Bull TV',
    country: 'AT',
    language: 'English',
    playlistId: STARTER_PLAYLIST_ID,
    isLive: true,
    resolution: '1080p' as any,
    currentProgram: {
      title: 'Extreme Mountain Biking & Cliff Diving World Series',
      description: 'High-adrenaline action sports, extreme athletic feats, and behind-the-scenes athlete documentaries.',
      startTime: Date.now() - 30 * 60 * 1000,
      endTime: Date.now() + 30 * 60 * 1000,
    },
  },
  {
    id: 'ch-arirang',
    name: 'Arirang World Culture TV',
    url: 'https://amdlive-ch01-ctnd-com.akamaized.net/arirang_1ch/smil:arirang_1ch.smil/playlist.m3u8',
    logo: 'https://images.unsplash.com/photo-1517154421773-0529f29ea451?w=150&auto=format&fit=crop&q=80',
    group: 'Culture & World',
    tvgId: 'Arirang.tv',
    tvgName: 'Arirang World',
    country: 'KR',
    language: 'English',
    playlistId: STARTER_PLAYLIST_ID,
    isLive: true,
    resolution: 'HD',
    currentProgram: {
      title: 'After School Club & Seoul Culture Beat',
      description: 'Korean arts, technology, pop culture, gastronomy, and international diplomacy discussions.',
      startTime: Date.now() - 12 * 60 * 1000,
      endTime: Date.now() + 48 * 60 * 1000,
    },
  },
  {
    id: 'ch-bunny-stream',
    name: 'CineLoop 24/7 High-Definition',
    url: 'https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8',
    logo: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=150&auto=format&fit=crop&q=80',
    group: 'Movies & Cinema',
    tvgId: 'CineLoop.tv',
    tvgName: 'CineLoop HD',
    country: 'NL',
    language: 'English',
    playlistId: STARTER_PLAYLIST_ID,
    isLive: true,
    resolution: 'FHD',
    currentProgram: {
      title: 'Open Source Animation Retrospective',
      description: 'Showcasing world-class open render animations, character rigging, and surround audio testing.',
      startTime: Date.now() - 18 * 60 * 1000,
      endTime: Date.now() + 42 * 60 * 1000,
    },
  },
  {
    id: 'ch-scitech',
    name: 'Sci-Tech Quantum World',
    url: 'https://cph-p2p-msl.akamaized.net/hls/live/200034/test/master.m3u8',
    logo: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=150&auto=format&fit=crop&q=80',
    group: 'Science & Tech',
    tvgId: 'SciTech.tv',
    tvgName: 'Sci-Tech Live',
    country: 'DK',
    language: 'English',
    playlistId: STARTER_PLAYLIST_ID,
    isLive: true,
    resolution: 'HD',
    currentProgram: {
      title: 'Deep Ocean Exploration & Coral Bio-Luminescence',
      description: 'Submersible research footage exploring benthic trenches and autonomous oceanic drone arrays.',
      startTime: Date.now() - 50 * 60 * 1000,
      endTime: Date.now() + 10 * 60 * 1000,
    },
  },
  {
    id: 'ch-euronews',
    name: 'Euronews International HD',
    url: 'https://euronews-euronews-world-1-au.samsung.wurl.tv/playlist.m3u8',
    logo: 'https://images.unsplash.com/photo-1495020689067-958852a7765e?w=150&auto=format&fit=crop&q=80',
    group: 'News & Current Affairs',
    tvgId: 'Euronews.eu',
    tvgName: 'Euronews',
    country: 'EU',
    language: 'English',
    playlistId: STARTER_PLAYLIST_ID,
    isLive: true,
    resolution: 'FHD',
    currentProgram: {
      title: 'European Parliament & Continental Ledger',
      description: 'Pan-European perspectives on trade, geopolitics, and green transition initiatives.',
      startTime: Date.now() - 8 * 60 * 1000,
      endTime: Date.now() + 52 * 60 * 1000,
    },
  },
];

export const SAMPLE_MOVIES: MovieItem[] = [
  {
    id: 'mov-tears-of-steel',
    title: 'Tears of Steel',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4',
    poster: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80',
    genre: ['Sci-Fi', 'Action', 'Cyberpunk'],
    year: 2012,
    duration: 734, // 12 mins
    description: 'In a dystopian future, a group of rebel warriors and eccentric scientists gather at the Oude Kerk in Amsterdam to stage a desperate holographic intervention and prevent an impending robot apocalypse.',
    rating: 4.8,
    playlistId: STARTER_PLAYLIST_ID,
    source: 'curated',
    resolution: '4K',
  },
  {
    id: 'mov-sintel',
    title: 'Sintel (The Search for Scales)',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/Sintel.mp4',
    poster: 'https://images.unsplash.com/photo-1578632767115-351597cf2477?w=600&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=1600&auto=format&fit=crop&q=80',
    genre: ['Fantasy', 'Adventure', 'Animation'],
    year: 2010,
    duration: 888, // 15 mins
    description: 'A lonely, resilient young woman named Sintel rescues and nurtures an injured baby dragon whom she names Scales. When the dragon is kidnapped by an adult beast, she embarks on a perilous quest across the continent.',
    rating: 4.9,
    playlistId: STARTER_PLAYLIST_ID,
    source: 'curated',
    resolution: 'FHD',
  },
  {
    id: 'mov-big-buck-bunny',
    title: 'Big Buck Bunny',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4',
    poster: 'https://images.unsplash.com/photo-1589656966895-2f33e7653819?w=600&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1509198397868-475647b2a1e5?w=1600&auto=format&fit=crop&q=80',
    genre: ['Animation', 'Comedy', 'Family'],
    year: 2008,
    duration: 596, // 10 mins
    description: 'A large, gentle rabbit wakes up to enjoy the spring morning and beautiful forest butterflies, only to find peace disrupted by three bullying forest critters. He sets up an ingenious Rube Goldberg vengeance trap.',
    rating: 4.7,
    playlistId: STARTER_PLAYLIST_ID,
    source: 'curated',
    resolution: 'FHD',
  },
  {
    id: 'mov-elephants-dream',
    title: "Elephants Dream",
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4',
    poster: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=600&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=1600&auto=format&fit=crop&q=80',
    genre: ['Sci-Fi', 'Surreal', 'Animation'],
    year: 2006,
    duration: 654,
    description: 'Proog and Emo navigate an immense, surreal mechanical universe constructed like an esoteric clockwork labyrinth. As tensions brew, reality fractures along psychological fault lines.',
    rating: 4.5,
    playlistId: STARTER_PLAYLIST_ID,
    source: 'curated',
    resolution: 'HD',
  },
  {
    id: 'mov-for-bigger-blazes',
    title: 'Chromatic Expedition',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    poster: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=600&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=1600&auto=format&fit=crop&q=80',
    genre: ['Nature', 'Documentary', 'Travel'],
    year: 2021,
    duration: 900,
    description: 'High-contrast cinematic photography documenting dramatic geological wonders, thermal pools, and auroral events across high-latitude volcanic terrains.',
    rating: 4.9,
    playlistId: STARTER_PLAYLIST_ID,
    source: 'curated',
    resolution: '4K',
  },
  {
    id: 'mov-subaru-drift',
    title: 'Apex Dynamics',
    url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/SubaruOutbackSeeTheWorld.mp4',
    poster: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=600&auto=format&fit=crop&q=80',
    backdrop: 'https://images.unsplash.com/photo-1492144534655-ae79c964c9d7?w=1600&auto=format&fit=crop&q=80',
    genre: ['Motorsport', 'Action', 'Documentary'],
    year: 2023,
    duration: 720,
    description: 'Precision racing engineering through mountain pass switchbacks, tracking aerodynamic performance and tire adhesion at the absolute limits of mechanical grip.',
    rating: 4.6,
    playlistId: STARTER_PLAYLIST_ID,
    source: 'curated',
    resolution: 'FHD',
  }
];

export const SAMPLE_M3U_TEMPLATE = `#EXTM3U x-tvg-url="https://iptv-org.github.io/epg/guides/us.guide.xml"
#EXTINF:-1 tvg-id="NASA.tv" tvg-name="NASA TV" tvg-logo="https://images.unsplash.com/photo-1614728894747-a83421e2b9c9?w=150" group-title="Science & Space" tvg-country="US",NASA TV Live Space Mission
https://ntv1.akamaized.net/hls/live/2014075/NASA-NTV1-HLS/master.m3u8

#EXTINF:-1 tvg-id="Bloomberg.us" tvg-name="Bloomberg Quicktake" tvg-logo="https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=150" group-title="Global News" tvg-country="US",Bloomberg Quicktake International
https://bblive-lh.akamaihd.net/i/bloomberg_live1@106822/master.m3u8

#EXTINF:-1 tvg-id="France24.en" tvg-name="France 24" tvg-logo="https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=150" group-title="Global News" tvg-country="FR",France 24 English HD
https://static.france24.com/live/F24_EN_LO_HLS/live_tv.m3u8

#EXTINF:-1 tvg-id="DW.en" tvg-name="DW English" tvg-logo="https://images.unsplash.com/photo-1504711434969-e33886168f5c?w=150" group-title="Global News" tvg-country="DE",Deutsche Welle HD Broadcast
https://dwamdstream102.akamaized.net/hls/live/2015525/dwstream102/index.m3u8

#EXTINF:-1 tvg-id="RedBull.tv" tvg-name="Red Bull TV" tvg-logo="https://images.unsplash.com/photo-1517649763962-0c623266ddc0?w=150" group-title="Action & Sports" tvg-country="AT",Red Bull TV Global Sports
https://rbmn-live.akamaized.net/hls/live/590964/BoRB-AT/master.m3u8

#EXTINF:-1 tvg-id="CineLoop.tv" tvg-name="CineLoop HD" tvg-logo="https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=150" group-title="Cinema & Movies" tvg-country="NL",CineLoop 24/7 Animation HD
https://test-streams.mux.dev/x36xhzz/x36xhzz.m3u8
`;
